### ISSUE TITLE
SimpleViewer using Xtion2 error

### ISSUE THREAD

**Issue by hi-kondo** [OpenNI/OpenNI2#106]
Hi, I am trying to run SimpleViewer in Ubuntu 14.04 using Xtion 2 ASUS, but I get below error
*****************************
Video Camera at /dev/video1 Detected
Depth Camera at /dev/video2 Detected
After initialization:

Creating Depth stream
Depth Stream start
Creating color stream
VID_STREAMON error 28, No space left on device

**************************************
I saw https://answers.ros.org/question/12582/usb_cam-vidioc_streamon-error-28/
and I did it, but this error appeared.

Could  you please help me?

**Comment by haolingyi** [comment]
you must you port for USB2.0
