### ISSUE TITLE
Reconnection loop to the sensor

### ISSUE THREAD

**Issue by iregon** [OpenNI/OpenNI2#109]
When I start OpenNI2 on ROS Kinetic with the command `roslaunch openni2_launch openni2.launch` it starts a continuous loop of reconnection to the sensor without any error.

A part of message showed is:

. . . 
[ WARN] [1530533003.851796857]: Detected loss of connection.  Stopping all streams and resetting device
[ INFO] [1530533007.235240341]: Device "1d27/0600@1/100" found.
[ INFO] [1530533007.851254498]: Detected re-connect...attempting reinit
[ INFO] [1530533008.908591795]: Re-applying configuration to camera on re-init
[ INFO] [1530533008.929105097]: Starting color stream to adjust camera
[ INFO] [1530533008.929701752]: Starting color stream.
[ INFO] [1530533008.994149364]: Restarting publishers, if needed
[ INFO] [1530533008.994949244]: Done re-initializing cameras
[ WARN] [1530533009.924432796]: Device "1d27/0600@1/100" disconnected

[ WARN] [1530533009.924909818]: Device "1d27/0600@1/100" disconnected

[ WARN] [1530533010.851467225]: Detected loss of connection.  Stopping all streams and resetting device
[ INFO] [1530533013.346860905]: Device "1d27/0600@1/104" found.
[ INFO] [1530533013.851728189]: Detected re-connect...attempting reinit
[ INFO] [1530533015.018626401]: Re-applying configuration to camera on re-init
[ INFO] [1530533015.041487448]: Starting color stream to adjust camera
[ INFO] [1530533015.042497378]: Starting color stream.
[ INFO] [1530533015.107487509]: Restarting publishers, if needed
[ INFO] [1530533015.108841390]: Done re-initializing cameras
[ WARN] [1530533016.306939896]: Device "1d27/0600@1/104" disconnected

[ WARN] [1530533016.307475772]: Device "1d27/0600@1/104" disconnected

[ WARN] [1530533016.851243668]: Detected loss of connection.  Stopping all streams and resetting device
[ INFO] [1530533019.735480141]: Device "1d27/0600@1/108" found.
[ INFO] [1530533019.851516723]: Detected re-connect...attempting reinit
[ INFO] [1530533021.408008103]: Re-applying configuration to camera on re-init
[ INFO] [1530533021.429622839]: Starting color stream to adjust camera
[ INFO] [1530533021.430399701]: Starting color stream.
[ INFO] [1530533021.493632167]: Restarting publishers, if needed
[ INFO] [1530533021.494297937]: Done re-initializing cameras
[ WARN] [1530533022.508973575]: Device "1d27/0600@1/108" disconnected

[ WARN] [1530533022.509527680]: Device "1d27/0600@1/108" disconnected
. . .

What am I doing wrong?

OS: Ubuntu mate 16.04
Sensor: Asus Xtion Pro Live
Platform: Raspberry Pi 3

**Comment by 130s** [comment]
- That output you posted is from ROS wrapper of OpenNI2 driver, so better to be discussed in ROS level.
- Discussion is continued [here](https://answers.ros.org/question/295938/openni2-reconnection-loop-to-the-sensor/).
