### ISSUE TITLE
OpenNI for Android

### ISSUE THREAD

**Issue by flombadil** [OpenNI/OpenNI2#15]
Hi, it seems to me, the compilation for android doesn't work.

I have set all the Paths and still get errors. Currently the error tells me the execinfo.h ist not found, if I delete the usage of execinfo.h it tells me that sys/sem.h is not found.

My Paths lead to the following things:

ARM_CXX = android-toolchain/bin/arm-linux-androideabi-g++
ARM_STAGING=android-toolchain/sysroot

So I have no idea how to compile it for android.

**Comment by eddiecohen** [comment]
Please see build instructions in https://github.com/OpenNI/OpenNI2/blob/develop/README.
Bottom line: building for Android is done via the Android NDK.
