### ISSUE TITLE
Memory leak of device generated frame

### ISSUE THREAD

**Issue by KHeresy** [OpenNI/OpenNI2#20]
I am working on my device module for OpenNI 2.2 Alpha(lastest source code).

I use NiViewer to test the Dummy device by excute the command "NiViewer.exe Dummy", and found that the memory usage is increasing fast.
After tracking the code, I found that the OniFrameInternal::refCount will never be zero, so the frame never been released.

According to the "DummyDevice" sample, it looks like that the stream should :
1. use "getServices().acquireFrame()" to generate a new OniFrame pointer. 
2. after fill all data to OniFrame, call raiseNewFrame() to trigger a new frame event

But if only do these, the created frame seem never been released.
If I release the frame by calling "getServices().releaseFrame()" after raiseNewFrame(), the problem semm be fixed.
Is this the correct way to generate a new frame?

I works in Visual C++ 2012 on Windows 7 x64.
Could someone please test this?

thanks.

**Comment by eddiecohen** [comment]
You're right of course. Fixed in ff1cc6cd360f9b9dbb3c12e8575dae3489b9a464.

**Comment by KHeresy** [comment]
Thanks for fix.

But it seems that the Kinect device also has this issue
https://github.com/KHeresy/OpenNI2/commit/fa968cba5213abe396c3c712987a9347c2467059

**Comment by eddiecohen** [comment]
Sorry for that. fixed in b509c8a26e5c01c20ebaf6f8e273f4c6ad54add7. Thanks for the update!
