### ISSUE TITLE
Can't turn of IR in NiViewer after runing

### ISSUE THREAD

**Issue by KHeresy** [OpenNI/OpenNI2#21]
In current version NiViewer, I can't turn on the IR stream after I execute the program.
I must execute NiViewer vai with the commad "-ir=on -color=off", which make color stream not available.
If there is no "-color=off" command, IR will never available.

I know I can only use IR or Color stream in the same time.
But I hope that I can switch IR / Color stream in the runtime, just like the version with OpenNI 2.1.

**Comment by eddiecohen** [comment]
Fixed in cd33b53e222e938dbcf73909493a2ca759c772d8
