### ISSUE TITLE
Unhandled exception in NiTE handtracker initializer after depth video mode change

### ISSUE THREAD

**Issue by msemegen** [OpenNI/OpenNI2#24]
Steps:
1. Change video mode in depth stream (640x480, 30FPS, PIXEL_FORMAT_DEPTH_100_UM)
2. Intialize HandTracker with device pointer

Result:
Unhandled exception at 0x61b7a1ba in my_debug.exe: 0xC0000005: Access violation reading location 0xbaadf00d.

Not sure if this is NiTE bug or OpenNI problem.

**Comment by eddiecohen** [comment]
The crash is a bug in NiTE.
But in any case, NiTE does not support depth formats other than 1 mm.
I asked NiTE guys to fix the crash, but it will return an error instead.
