### ISSUE TITLE
Source code download URL / repository tags

### ISSUE THREAD

**Issue by ryandesign** [OpenNI/OpenNI2#36]
I am a manager of the MacPorts project and we have been asked to [include openni2 in MacPorts](https://trac.macports.org/ticket/40107). (We already have openni 1.) What is the intended mechanism for users to download the source code of openni 2.2.0.30, or generally any given version of openni2? I expected to find tags in your github repository, as there were for openni 1, but there aren't any tags here for openni 2.2.x.

**Comment by andreacfromtheapp** [comment]
bump. +1. we need the source code for packaging too. 
please.

**Comment by eddiecohen** [comment]
Sorry, it was missing. I just added it.

Source code for packaging is there as well - see README file for details.
