### ISSUE TITLE
add android make files to Wrapper folder and its sub folders

### ISSUE THREAD

**Issue by christiankerl** [OpenNI/OpenNI2#38]
or is there a special reason, that this wrapper is not included in the android build?

**Comment by eddiecohen** [comment]
Actually, there is a reason for that. 
Current OpenNI solution for Android is only for native usage (i.e. when running as part of the system). In this configuration, the java API is meaningless.
Having OpenNI exposed to applications is a bit more complicated then having java APIs. Some problems that need to be addressed are:
- USB device permissions - the application needs to get specific permissions to the USB device
- Access to files. OpenNI (and NiTE) assume some files are installed as part of the installation process, which is a bit different when using APKs.

In any case, we're currently working on a complete Android solution.

**Comment by christiankerl** [comment]
is there any time schedule for the android solution?

**Comment by eddiecohen** [comment]
I should have a first unstable version in the coming days.

**Comment by christiankerl** [comment]
thanks for the info, because I'm currently hacking my own version

**Comment by eddiecohen** [comment]
Everything is committed to 'develop'. Enjoy!

**Comment by christiankerl** [comment]
ok, I will give it a try. on which device/android version did you test the code?

**Comment by eddiecohen** [comment]
I tested it on an Asus Transformer with Android 4.2.

**Comment by christiankerl** [comment]
ok, works for me on Nexus 7 (2013) and Android 4.3, thanks a lot

just in case someone reads this: because of a bug in the Nexus 7 Android version the language has to be set to English (US) otherwise the PS1080 is not recognized by the Android USB API and the OpenNI2 Android SDK won't work
