### ISSUE TITLE
Building with older compilers (e.g. current g++ in Xcode) fails compiling XN_API_DEPRECATED

### ISSUE THREAD

**Issue by dankegel** [OpenNI/OpenNI2#39]
When using g++ (as opposed to c++), which reports itself as
i686-apple-darwin11-llvm-g++-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)
the build fails with
../Include/XnOS.h:445: error: wrong number of arguments specified for 'deprecated' attribute

I currently use this patch to work around it:

--- a/ThirdParty/PSCommon/XnLib/Include/Linux-x86/XnPlatformLinux-x86.h
+++ b/ThirdParty/PSCommon/XnLib/Include/Linux-x86/XnPlatformLinux-x86.h
@@ -176,7 +176,11 @@ typedef size_t             XnSizeT;
 #define XN_API_IMPORT 

 /*\* Indicates a deprecated function */
+#if defined(**clang**) || (**GNUC** > 4 || (**GNUC** == 4 && (**GNUC_MINOR** > 4)))
 #define XN_API_DEPRECATED(msg) **attribute**((deprecated("This function is deprecated: " msg)))
+#else
+#define XN_API_DEPRECATED(msg)
+#endif

 #define XN_DEPRECATED_WARNING_IDS  
 #define XN_HIDES_PARENT_METHOD_WARNING_ID

**Comment by eddiecohen** [comment]
Should be fixed by f83b28f885ab3a09bdb398845bc33345732ac91f.
