### ISSUE TITLE
"ReleaseVersion.py android" on develop branch causes "Can't find ANDROID_CXX and ANDROID_STAGING"

### ISSUE THREAD

**Issue by christiankerl** [OpenNI/OpenNI2#40]
if I try to build the latest android version from the develop branch I get the following error. any ideas how I have to define these vars?

```
OpenNI2-dev/Packaging$ ./ReleaseVersion.py android
Creating installer for OpenNI 2.3 android
Traceback (most recent call last):
  File "./ReleaseVersion.py", line 196, in <module>
    subprocess.check_call(['make', '-C', '../', '-j' + calc_jobs_number(), 'PLATFORM=' + plat, 'clean'], stdout=devNull, stderr=devNull)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-C', '../', '-j2', 'PLATFORM=android', 'clean']' returned non-zero exit status 2
```

if I type the command manually I get:

```
OpenNI2-dev/Packaging$ make -C ../ -j2 PLATFORM=android clean
make: Entering directory `OpenNI2-dev'
ThirdParty/PSCommon/BuildSystem/CommonDefs.mak:36: *** Cross-Compilation error. Can't find ANDROID_CXX and ANDROID_STAGING.  Stop.
make: Leaving directory `OpenNI2-dev'
```

**Comment by eddiecohen** [comment]
Please note that README file has changed a bit (https://github.com/OpenNI/OpenNI2/tree/develop).

You should actually run "ReleaseVersion.py Android" with a capital A.

**Comment by christiankerl** [comment]
ah ok, sorry, it works now, thanks a lot.

maybe the README should mention that one needs to install the SDK for API level 12 (SimpleRead and SimpleViewer) and 18 (NiViewer) using the Android SDK Manager?!

**Comment by eddiecohen** [comment]
I updated the README file (583777c744a79638839ec5f28b7e2062210cf97a).
