### ISSUE TITLE
Building with older compilers fails on "#pragma GCC diagnostic push"

### ISSUE THREAD

**Issue by dankegel** [OpenNI/OpenNI2#42]
Older compilers (like the g++ that comes with XCode) complain:

../../../Include/OpenNI.h:88: warning: expected [error|warning|ignored] after ‘#pragma GCC diagnostic’

88 #pragma GCC diagnostic push

../../../Include/OpenNI.h:92: warning: expected [error|warning|ignored] after ‘#pragma GCC diagnostic’

92 #pragma GCC diagnostic pop

The workaround is to not use that pragma with older compilers; here's a patch.
https://gist.github.com/dankegel/6709336

**Comment by eddiecohen** [comment]
Fixed in f83b28f885ab3a09bdb398845bc33345732ac91f.
