### ISSUE TITLE
OpenNI2 packaging scripts are source-incompatible with Python3

### ISSUE THREAD

**Issue by jeadorf** [OpenNI/OpenNI2#48]
The python scripts Packaging/ReleaseVersion.py and Packaging/Harvest.py are only compatible with Python 2.x. Hence, the interpreters should be set to python2 rather than python in the corresponding shebang. See PEP 0394 http://www.python.org/dev/peps/pep-0394 for the rationale. On Arch Linux which afaik is the first distro to adopt Python3 as default (other distros will follow suit sooner or later), the packaging scripts of OpenNI2 fail.

Here is the patch:

```
diff --git a/Packaging/Harvest.py b/Packaging/Harvest.py
index 4ce9ed2..42b3d61 100755
--- a/Packaging/Harvest.py
+++ b/Packaging/Harvest.py
@@ -1,4 +1,4 @@
-#!/usr/bin/python
+#!/usr/bin/python2

 #/****************************************************************************
 #*                                                                           *
diff --git a/Packaging/ReleaseVersion.py b/Packaging/ReleaseVersion.py
index e2fdf5f..3ba2cf3 100755
--- a/Packaging/ReleaseVersion.py
+++ b/Packaging/ReleaseVersion.py
@@ -1,4 +1,4 @@
-#!/usr/bin/python
+#!/usr/bin/python2

 #/****************************************************************************
 #*       
```

**Comment by eddiecohen** [comment]
Cherry-picked on f761244cfd3f643c17468ab64cb07e47b0080f67.
