### ISSUE TITLE
Distribution archive is assigned wrong name due to empty PRODUCT_STRING

### ISSUE THREAD

**Issue by jeadorf** [OpenNI/OpenNI2#49]
The Makefile uses the default Python interpreter instead of a Python 2.x interpreter in order to construct the PRODUCT_STRING, which is used for naming the distribution archive. See http://www.python.org/dev/peps/pep-0394, here python2 should be used for interpreting python commands that are source-incompatible with Python3.

Here is the patch:

```
diff --git a/Makefile b/Makefile
index a436a84..d0d47d0 100644
--- a/Makefile
+++ b/Makefile
@@ -24,7 +24,7 @@ ifeq ("$(OSTYPE)","Darwin")
 else
        OS_NAME = Linux
 endif
-PRODUCT_STRING = OpenNI-$(OS_NAME)-$(PLATFORM)-$(shell cd Packaging && python -c "import UpdateVersion; print UpdateVersion.getVersion
+PRODUCT_STRING = OpenNI-$(OS_NAME)-$(PLATFORM)-$(shell cd Packaging && python2 -c "import UpdateVersion; print UpdateVersion.getVersio
 FINAL_DIR = Packaging/Final

 OPENNI = Source/Core
```

Related to issue https://github.com/OpenNI/OpenNI2/issues/48

**Comment by eddiecohen** [comment]
Merged into develop at f761244cfd3f643c17468ab64cb07e47b0080f67
