### ISSUE TITLE
Building OpenNI.sln with vc2010 Express

### ISSUE THREAD

**Issue by rh-galaxy** [OpenNI/OpenNI2#5]
....\Resources\OpenNI.rc(10): fatal error RC1015: cannot open include file 'afxres.h'.
...
========== Build: 2 succeeded, 14 failed, 0 up-to-date, 0 skipped ==========

I suggest replacing afxres.h with winres.h in OpenNI.rc, or removing the include.
See http://stackoverflow.com/questions/3566018/cannot-open-include-file-afxres-h-in-vc2010-express

**Comment by eddiecohen** [comment]
fixed in commit 633968efd8d0b017cf5778e3792095362a14b36c
