### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by ryandesign** [OpenNI/OpenNI2#53]
The file LICENSE says the license is Apache 2.0 but the file Packaging/Linux/install.sh says the license is GPL 3 or later. Which is it?

**Comment by eddiecohen** [comment]
OpenNI is under Apache license. The install.sh file contains a mistake. I will fix it soon.

**Comment by eddiecohen** [comment]
Fixed on 2020ade6698060c848d5399e864b26594be9727e.
