### ISSUE TITLE
Does OpenNI2 support Registration of Kinect?

### ISSUE THREAD

**Issue by wpjsolo** [OpenNI/OpenNI2#55]
The Driver Libfreenect can provide  a mode that output registration depth data.
Can OpenNI2 support that when the Driver is libfreenect?

**Comment by eddiecohen** [comment]
OpenNI has a method for it: Device.setImageRegistrationMode().
However, I'm not familiar with a libfreenect driver for OpenNI...

**Comment by wpjsolo** [comment]
I use that method by:
if (device.isImageRegistrationModeSupported(openni::IMAGE_REGISTRATION_DEPTH_TO_COLOR))
{
        device.setImageRegistrationMode(openni::IMAGE_REGISTRATION_DEPTH_TO_COLOR);
        qDebug()<<"Registration OK!";
}
It print out "Registration OK!" every time.But the depth data and rgb data remain unregistrated.
How can I use it properly?

The introductions about libfreenect driver for OpenNI
https://github.com/piedar/OpenNI2-FreenectDriver
https://github.com/OpenKinect/libfreenect
http://community.openni.org/openni/topics/how_can_i_align_with_kinect

**Comment by eddiecohen** [comment]
In that case, it's probably a bug in OpenNI2-FreenectDriver.
By the way, did you check the return code from setImageRegistrationMode()?

**Comment by tomoto** [comment]
Hi wpjsolo,

I have several suggestions.
1. Call setImageRegistrationMode() _after_ starting the depth and image stream. setImageRegistrationMode() may not work before starting the streams due to the internal objects not yet created.
2. As suggested by Eddie, check the return code of setImageRegistrationMode().
3. If your call sequence and return code are correct but the problem still exists, file a report to https://github.com/piedar/OpenNI2-FreenectDriver .

**Comment by wpjsolo** [comment]
Dear tomoto and eddiecohen:
I pull up my Openni2 and FreenectDriver.
I checked my call sequence ,it's right.And the the return code is 0(openni::STATUS_OK).
I also run libfreenect sample regview and Openni2 sample simpleviewer, the first is right and the second is wrong.
I wrote a temp blog to show details picture on http://blog.fishcy.com/?p=12 
Can you give me some more advice? Thanks a lot!

**Comment by eddiecohen** [comment]
So the bug is probably not in libfreenect (as its sample works), and not in OpenNI (as you get an OK status). As I said before, it seems the bug is in OpenNI2-FreenectDriver project...

**Comment by tomoto** [comment]
Hi wpjsolo,

I see you reported this issue to https://github.com/piedar/OpenNI2-FreenectDriver . I think Benn (the author of OpenNI2-FreenectDriver) could help you.

**Comment by wpjsolo** [comment]
Dear Tomoto and eddiecohen:
  Thank you very much for patient answer.It's probably a bug of Freenect-Driver.
  Apart from waiting the answer of the author of OpenNI2-FreenectDriver. Could you be kind enough to tell me some other way to use OpenNI2 on Linux with Nite2 and registration working well?

**Comment by tomoto** [comment]
If you cannot wait, the answer is straightforward: read the source code and solve the problem by yourself, which I myself usually do under the same situation. Enjoy and Happy Hacking!

**Comment by wpjsolo** [comment]
Dear tomoto:
     I find out the bugs in Freenect-Driver and add a pull request.
     https://github.com/piedar/OpenNI2-FreenectDriver/pull/44
     Thanks again!
     It's really happy.^_^

**Comment by tomoto** [comment]
Congratulations!

**Comment by hadisaadat** [comment]
Dear wpjsolo
I have the same problem, could you tell me how did you solve it?

**Comment by michaelwolfram** [comment]
For me it was enough to check the call sequence of the OpenNI functions.
Checking the availability and enabling the registration AFTER the creation of the color and depth streams changed the return code of setImageRegistrationMode() from 4 to 0.
