### ISSUE TITLE
Add README.md to announce this repository is no longer maintained

### ISSUE THREAD

**Issue by tomoto** [OpenNI/OpenNI2#83]
I still see people sending issue reports and pull requests to this repository without knowing it is no longer maintained or where to go instead. To avoid further confusion, I think it could be a good idea to put README.md to announce this repository is no longer maintained and guide the audience to more appropriate place. I can do it because I am probably one of only a few non-Primesense people who can modify this repository.

The README.md would look like this. If there is no objection to this idea, I will do it probably before long.
https://github.com/tomoto/OpenNI2

If you want to have your name in the list as a volunteer, please let me know.

**Comment by piedar** [comment]
:+1:

**Comment by huangfuyang** [comment]
Thanks for reminding

**Comment by KHeresy** [comment]
I think that is a good idea to highlight it in main page.

But just want to know, is it possible to continue using this repo since you have the permission to modify this repo?

BTW, I think the repo with OpenNI account is much better...
Is it possible to ask PrimeSense release this account?
(Maybe we should ask ASUS to do this, since they are another pioneer member of OpenNI )

**Comment by tomoto** [comment]
Thanks for your feedback, everyone.

I am given the modify (write) permission but not the admin (owner) permission. Meaning, I cannot invite another collaborators and I will be probably only one committer to this repository forever. It is not going to work and I am not willing to.

If anybody is willing to take the ownership of OpenNI account, I think he/she may talk to the current owners to negotiate and make an arrangement. (I am not sure if they are allowed to respond, though.) In any ways, someone has to volunteer himself/herself to take the responsibility for owning it first and initiate the conversation. Heresy, are you saying you or your group will volunteer yourself?

**Comment by tomoto** [comment]
According to https://github.com/OpenNI?tab=activity , every member (except myself) seems ex-Primesense and now in Apple.

IMHO, taking the ownership of OpenNI account is not a trivial responsibility because it also implies taking the leadership of the community. For example, if someone took OpenNI account ownership, then we would have two repositories in the world, i.e. OpenNI and Occipital. To avoid unnecessary confusion and competition, the new OpenNI owner would need to negotiate with Occipital and agree on integrating and/or co-owning one OpenNI repository if he/she really wanted to contribute to the community's happiness. (Or, they might possibly agree on maintaining two separate repositories if both organizations' visions were different.) It is just my personal opinion, but I feel a volunteer who wants to succeed to the name of OpenNI should (ideally) have a certain vision and leadership upon the entire community.

**Comment by KHeresy** [comment]
I understand, and totally agree your point.
Owning the OpenNI account means become the leader of OpenNI group, or the manager of the group.
That is the reason why I think PrimeSense should not own this account since they do want to maintain OpenNI in the future.

(BTW, I don't think I have the capacity to do this...)

**Comment by tomoto** [comment]
Thanks. I do not think I have that capacity either, so now I just thank to Occipital and just try to help people reach there.

**Comment by tomoto** [comment]
Merged #84  and #85.

It is so sad that I have to do this, but probably it is good thing for the future.
